name: Build & Push Docker Images to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version tag
        id: vars
        run: |
          REPO="${{ github.repository }}"
          REPO_NAME=$(basename "$REPO" | tr '[:upper:]' '[:lower:]')
          BRANCH="${GITHUB_REF##*/}"
          # BRANCH_NAME=master 
          # $(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | tr '/' '_')
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          BUILD_NUMBER="${{ github.run_number }}"
          VERSION_TAG="1.0.${BUILD_NUMBER}"
          IMAGE_NAME="ghcr.io/${OWNER_LOWER}/${REPO_NAME}_${BRANCH_NAME}"

          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "owner=$OWNER_LOWER" >> $GITHUB_OUTPUT
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        run: |
          docker build -t ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.version_tag }} \
                       -t ${{ steps.vars.outputs.image_name }}:latest .
          docker push ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.version_tag }}
          docker push ${{ steps.vars.outputs.image_name }}:latest

      - name: Export version to downstream workflow
        run: |
          echo "VERSION_TAG=${{ steps.vars.outputs.version_tag }}" >> $GITHUB_ENV

      - name: Notify k8s-infra repo to deploy new image
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.K8S_INFRA_DISPATCH_TOKEN }}
          repository: Derint/k8s-infra
          event-type: update-deployment
          client-payload: >-
            {
              "repo": "${{ steps.vars.outputs.repo_name }}",
              "branch": "${{ steps.vars.outputs.branch_name }}",
              "image": "${{ steps.vars.outputs.image_name }}",
              "version": "${{ steps.vars.outputs.version_tag }}"
            }
